[package]
name = "symbolic_expressions"
version = "0.3.6"
authors = ["Joost Damad <joost@productize.be>"]
license = "MIT"
description = "A symbolic-expression parser/writer"
repository = "https://github.com/productize/symbolic-expressions"
keywords = ["sexp","s-exp","symbolic","kicad"]

[features]
nightly = []
nightly-testing = ["clippy", "nightly"]

[dependencies]
nom = "~1.2.0"
clippy = { version = "0.*", optional = true }
