[package]
name = "symbolic_expressions"
version = "4.0.2"
authors = ["Joost Damad <joost@productize.be>"]
license = "MIT/Apache-2.0"
description = "A symbolic-expression parser/writer"
repository = "https://github.com/productize/symbolic-expressions"
keywords = ["sexp","s-exp","symbolic","kicad"]
documentation = "https://docs.rs/symbolic_expressions"

[dependencies]
error-chain = "0.8"
